<?php

declare(strict_types=1);

namespace Application\Migration;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

class Version20260724010736 extends AbstractMigration
{
    public function up(Schema $schema): void
    {
        // added manually to run first
        $this->addSql('ALTER TABLE account DROP COLUMN budget_balance');
        $this->addSql('ALTER TABLE account DROP CONSTRAINT CONSTRAINT_1');
        $this->addSql('ALTER TABLE account MODIFY balance INT DEFAULT 0');
        $this->addSql('UPDATE account SET balance = total_balance WHERE type = \'group\'');
        $this->addSql('ALTER TABLE account CHANGE total_balance_former balance_former INT NOT NULL DEFAULT 0');

        // generated by doctrine
        $this->addSql('ALTER TABLE account ADD budget_balance INT AS (IF(type = \'asset\', budget_allowed - (balance - balance_former), budget_allowed - balance)) PERSISTENT, DROP total_balance');

        // added manually to run after
        $this->addSql('ALTER TABLE account ADD CONSTRAINT `leaf_balance_not_null` CHECK (`type` = \'group\' OR `balance` IS NOT NULL)');
    }
}
